<?php
return [
// Социальные сети и видеохостинги.
'vk.com','vkontakte.ru','userapi.com','tiktok.com','tiktokcdn.com','musical.ly','rutube.ru','meta.com','instagram.com',
// Интернет-магазины.
'ozon.ru','wildberries.ru','market.yandex.ru','aliexpress.ru','aliexpress.com','amazon.com','ebay.com','lamoda.ru','citilink.ru','dns-shop.ru','eldorado.ru','mvideo.ru','sbermegamarket.ru','leroymerlin.ru','castorama.ru','fixprice.ru','perekrestok.ru','magnit.ru','lenta.com','auchan.ru','okeydostavka.ru',
// Государственные сервисы.
'gosuslugi.ru','gosuslugi.mos.ru','reestr-povestok.ru','fssp.gov.ru','kad.arbitr.ru','my.arbitr.ru','gks.ru','rosstat.gov.ru','nalog.gov.ru','npd.nalog.ru','rosreestr.gov.ru','mos.ru','gov.ru','minfin.gov.ru','rkn.gov.ru',
// Финансы и криптовалюты.
'qiwi.com','qiwi.ru','yoomoney.ru','paypal.com', 'binance.com','bybit.com','huobi.com','kucoin.com', 'lbank.com','mexc.com','gate.io','bitget.com','bitmart.com','xt.com','bit.com','deribit.com','delta.exchange','bitmex.com','kraken.com','coinbase.com','bittrex.com','gemini.com','crypto.com','ftx.com','okx.com','bitfinex.com','bitstamp.net','poloniex.com','bithumb.com','upbit.com','coinone.co.kr','korbit.co.kr','gopax.co.kr','cash.app','venmo.com','revolut.com','wise.com','remessaonline.com.br','nubank.com.br','inter.com.br','itau.com.br','santander.com.br','bradesco.com.br','bb.com.br','caixa.gov.br','banco.br','bancointer.com.br','neon.com.br','c6bank.com.br','next.me','pagseguro.com.br','mercadopago.com.br','picpay.com','n26.com','monzo.com','starlingbank.com','curve.com','bunq.com',
// Банки.
'sberbank.ru','vtb.ru','gazprombank.ru', 'alfabank.ru', 'raiffeisen.ru','uralsib.ru','rosbank.ru','rshb.ru','domrfbank.ru','sovcombank.ru','rencredit.ru','homecredit.ru','unicredit.ru','open.ru','mdm.ru','cbonds.ru','expobank.ru','rosneftbank.ru','absolutbank.ru','avangard.ru','binbank.ru','bbr.ru','chelinvest.ru','cibank.ru','csas.cz','delo.ru','dkibank.ru','dks.ru','euroalliance.ru','europlanbank.ru', 'factoring.ru','finservice.ru','finam.ru','forabank.ru','forward-bank.com','genbank.ru','geobank.ru','glavbank.ru','goldman.ru','ingbank.ru','intesasanpaolo.ru','ipb.ru','izhcombank.ru','kbc.com','kdb.ru','klikbca.com','kredprombank.ru','kredobank.com.ua','kuzbasshimbank.ru','levoberezhny.ru','liberbank.ru','lokomotivbank.ru','m2mbank.ru', 'maxima.ru','mbbru.com','metallinvestbank.ru','mibank.ru','micex.ru','moscombank.ru','mspbank.ru','mtb.ru','mufg.jp','nefteprombank.ru','newbank.ru','nokssbank.ru','nrb.ru','nw1bank.ru','ocbc.com','oilbank.ru','orient-express.ru','ostrova.ru','pashabank.ru','peregrine.ru','petrocommerce.ru','pfbank.ru','pib.ru','pnc.com','postbank.ru','premiercredit.ru','primbank.ru','priorbank.ru','profbank.ru','promenergobank.ru','prominvestbank.ru','promsvyazbank.ru','psbank.ru','qbancorp.com','rba.ru','rbinvest.ru','regnum.ru','renins.ru','resocreditbank.ru','rgsbank.ru','riverbank.ru','roibank.ru','rosavtobank.ru','rosdorbank.ru','rosevrobank.ru','rosinterbank.ru','rosprombank.ru','rosselkhozbank.ru','rostbank.ru','rsb.ru','rtb.ru','rublev.ru','russobank.com','russwholesale.ru','ryabank.ru','sistemabank.ru','skbbank.ru','skbkontur.ru','skb-prizma.ru','slavbank.ru','snbank.ru','solidbank.ru','spb.ru','stavropolbank.ru','stroylkredit.ru','sumitomomitsui.co.jp','swedbank.ru','tatsotsbank.ru','tcb.ru','territorial.ru','tkbbank.ru','torgovyi.ru','transcapitalbank.ru','trast.ru','tsbank.ru','ubrr.ru','umcu.ru','unicombank.ru','uniqa.ru','uralprombank.ru','uralfd.ru','vfbank.ru','vladbiznesbank.ru','vostbank.ru','vrbb.ru','vuzbank.ru','westlb.de','zapsibkombank.ru','zenit.ru',
//Мусорные сервисы.
'dropbox.com', 'ccleaner.com','hoyoverse.com','hoyolab.com','roblox.com'
];